//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogHeThong
    {
        public System.DateTime ThoiGian { get; set; }
        public string MaNV { get; set; }
        public string MaDoiTuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
