//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyClinicEntities : DbContext
    {
        public MyClinicEntities()
            : base("name=MyClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<ChiDinhDungThuoc> ChiDinhDungThuocs { get; set; }
        public virtual DbSet<CT_DanhSachKham> CT_DanhSachKham { get; set; }
        public virtual DbSet<CT_ThongKe> CT_ThongKe { get; set; }
        public virtual DbSet<DanhSachKham> DanhSachKhams { get; set; }
        public virtual DbSet<DonViThuoc> DonViThuocs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LogHeThong> LogHeThongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuKham> PhieuKhams { get; set; }
        public virtual DbSet<PhieuNhapThuoc> PhieuNhapThuocs { get; set; }
        public virtual DbSet<PhieuThuChi> PhieuThuChis { get; set; }
        public virtual DbSet<QuyDinh> QuyDinhs { get; set; }
        public virtual DbSet<SoKhamBenh> SoKhamBenhs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Thuoc> Thuocs { get; set; }
    }
}
