//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiDinhDungThuoc
    {
        public string MaPK { get; set; }
        public string MaThuoc { get; set; }
        public int SoLuong { get; set; }
        public string MaDV { get; set; }
        public int LieuLuong { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhieuKham PhieuKham { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
