//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_ThongKe
    {
        public int ID { get; set; }
        public int TongThu { get; set; }
        public int TongChi { get; set; }
        public int LuotKham { get; set; }
        public int SLThuocNhap { get; set; }
        public string LoaiThoiGian { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
    }
}
