//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int TongTienThanhToan { get; set; }
        public bool TrangThaiThanhToan { get; set; }
        public bool TrangThaiGiaoThuoc { get; set; }
        public string MaNVThanhToan { get; set; }
        public string MaNVGiaoThuoc { get; set; }
        public string MaBN { get; set; }
    
        public virtual SoKhamBenh SoKhamBenh { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
    }
}
