//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThuChi
    {
        public string MaPhieu { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int LoaiPhieu { get; set; }
        public int GiaTri { get; set; }
        public string NoiDung { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
