//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.ChiDinhDungThuocs = new HashSet<ChiDinhDungThuoc>();
        }
    
        public string MaPK { get; set; }
        public string MaBN { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public string ChanDoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiDinhDungThuoc> ChiDinhDungThuocs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SoKhamBenh SoKhamBenh { get; set; }
    }
}
