//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongPhongMachTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public string MaQD { get; set; }
        public string TenQD { get; set; }
        public string KieuGiaTri { get; set; }
        public string GiaTriLonNhat { get; set; }
        public string GiaTriNhoNhat { get; set; }
    }
}
